import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Web3Provider from "./Web3Provider";
// import MarketplaceDemo from "./MarketplaceDemo";

// Remove Geist font setup due to missing export

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Web3Provider>
          {/* <MarketplaceDemo /> */}
          {children}
        </Web3Provider>
      </body>
    </html>
  );
}
